theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
mouse = true
middle-click-paste = true
scroll-lines = 3
shell = ["zsh", "-c"]
text-width = 80
completion-trigger-len = 2
auto-completion = true
auto-format = true
idle-timeout = 400
preview-completion-insert = true
completion-replace = false
auto-info = true
true-color = true
undercurl = true
color-modes = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "position", "file-encoding"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 25

[editor.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'

[editor.search]
smart-case = true
wrap-around = true

[editor.whitespace]
# render = "selection"
# characters = { space = "·", nbsp = "⍽", tab = "→", newline = "⏎" }
# 
[editor.indent-guides]
render = true
character = "┊"
skip-levels = 1

[editor.gutters]
layout = ["diff", "diagnostics", "line-numbers", "spacer"]

[editor.soft-wrap]
enable = true
[keys.normal]
C-s = ":w"
C-q = ":q"
C-f = "format_selections"
C-c = "toggle_comments"

[keys.normal.z]
z = "align_view_center"
t = "align_view_top"
b = "align_view_bottom"

[keys.insert]
C-s = ["commit_undo_checkpoint", ":w"]
j = { k = "normal_mode" }

[keys.select]
C-s = ["normal_mode", ":w"]
