# Language Servers
[language-server.gopls]
command = "gopls"

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.zls]
command = "zls"

# Go Configuration
[[language]]
name = "go"
language-servers = ["gopls"]
auto-format = true

# Python Configuration
[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

# Zig Configuration
[[language]]
name = "zig"
language-servers = ["zls"]
auto-format = true
