---
- name: Install Hyprland and desktop packages
  ansible.builtin.dnf:
    name: "{{ hyprland_packages }}"
    state: present
  become: yes

- name: Create Hyprland config directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - hypr
    - waybar
    - mako
    - wofi

- name: Generate Hyprland configuration
  ansible.builtin.template:
    src: hyprland.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/hypr/hyprland.conf"
    mode: '0644'

- name: Generate Waybar configuration
  ansible.builtin.template:
    src: waybar.json.j2
    dest: "{{ ansible_env.HOME }}/.config/waybar/config"
    mode: '0644'

- name: Generate Waybar styling
  ansible.builtin.template:
    src: waybar.css.j2
    dest: "{{ ansible_env.HOME }}/.config/waybar/style.css"
    mode: '0644'

- name: Generate Wofi styling
  ansible.builtin.template:
    src: wofi.css.j2
    dest: "{{ ansible_env.HOME }}/.config/wofi/style.css"
    mode: '0644'

- name: Generate Mako configuration
  ansible.builtin.template:
    src: mako.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/mako/config"
    mode: '0644'

- name: Generate Hyprlock configuration
  ansible.builtin.template:
    src: hyprlock.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/hypr/hyprlock.conf"
    mode: '0644'

- name: Generate Hypridle configuration
  ansible.builtin.template:
    src: hypridle.conf.j2
    dest: "{{ ansible_env.HOME }}/.config/hypr/hypridle.conf"
    mode: '0644'

- name: Create Hyprland TTY launch script
  ansible.builtin.template:
    src: hyprland-tty-launch.sh.j2
    dest: "{{ ansible_env.HOME }}/.local/bin/start-hyprland"
    mode: '0755'