---
- name: Install Hyprland and desktop packages
  ansible.builtin.dnf:
    name: "{{ hyprland_packages }}"
    state: present
  become: yes

- name: Create Hyprland config directories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - hypr
    - waybar
    - mako
    - wofi

