---
- name: Install GUI applications (macOS)
  community.general.homebrew_cask:
    name: "{{ gui_packages_macos }}"
    state: present
  when: ansible_os_family == "Darwin"

- name: Add Flathub repository (Linux)
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: yes
  when: ansible_os_family == "RedHat"

- name: Install GUI applications via Flatpak (Linux)
  community.general.flatpak:
    name: "{{ gui_packages_linux }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Setup Hyprland desktop environment (Linux)
  include_tasks: hyprland.yml
  when: ansible_os_family == "RedHat"