---
- name: Install Flatpak
  ansible.builtin.package:
    name: flatpak
    state: present
  become: true

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: "{{ flatpak_remote_name }}"
    flatpakrepo_url: "{{ flatpak_remote_url }}"
    state: present
  become: true

- name: Install Flatpak applications
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpak_applications | default([]) }}"
  become: true
  when: flatpak_applications is defined