---
- name: Set package manager facts
  ansible.builtin.set_fact:
    current_package_manager: "{{ package_managers[ansible_os_family] }}"

- name: Include macOS package management tasks
  ansible.builtin.include_tasks: macos.yml
  when: ansible_os_family == "Darwin"

- name: Include RedHat/Fedora package management tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Include Flatpak management tasks
  ansible.builtin.include_tasks: flatpak.yml
  when: 
    - ansible_os_family != "Darwin"
    - flatpak_applications is defined
    - flatpak_applications | length > 0