---
- name: Install zsh (Fedora)
  ansible.builtin.dnf:
    name: zsh
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Set zsh as default shell
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/zsh
  become: yes
  when: ansible_os_family != "Darwin"

