---
- name: Install Hyprland core packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_core_packages_linux }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_core
  tags: hyprland

- name: Install Hyprland core packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_core_packages_linux }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_core
  tags: hyprland

- name: Install status bar packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_status_bars }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_status_bars
  ignore_errors: yes
  tags: hyprland

- name: Install status bar packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_status_bars }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_status_bars
  ignore_errors: yes
  tags: hyprland

- name: Install launcher packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_launchers }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_launchers
  ignore_errors: yes
  tags: hyprland

- name: Install launcher packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_launchers }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_launchers
  ignore_errors: yes
  tags: hyprland

- name: Install clipboard manager packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_clipboard_managers }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_clipboard
  ignore_errors: yes
  tags: hyprland

- name: Install clipboard manager packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_clipboard_managers }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_clipboard
  ignore_errors: yes
  tags: hyprland

- name: Install file manager packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_file_managers }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_file_managers
  ignore_errors: yes
  tags: hyprland

- name: Install file manager packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_file_managers }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_file_managers
  ignore_errors: yes
  tags: hyprland

- name: Install notification daemon packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_notification_daemons }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_notifications
  ignore_errors: yes
  tags: hyprland

- name: Install notification daemon packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_notification_daemons }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_notifications
  ignore_errors: yes
  tags: hyprland

- name: Install screenshot tool packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_screenshot_tools }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_screenshots
  ignore_errors: yes
  tags: hyprland

- name: Install screenshot tool packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_screenshot_tools }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_screenshots
  ignore_errors: yes
  tags: hyprland

- name: Install audio tool packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_audio_tools }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_audio
  ignore_errors: yes
  tags: hyprland

- name: Install audio tool packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_audio_tools }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_audio
  ignore_errors: yes
  tags: hyprland

- name: Install system utility packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_system_utilities }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_system_utils
  ignore_errors: yes
  tags: hyprland

- name: Install system utility packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_system_utilities }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_system_utils
  ignore_errors: yes
  tags: hyprland

- name: Install terminal emulator packages (Fedora/RedHat)
  ansible.builtin.dnf:
    name: "{{ hyprland_terminals }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat" and hyprland_install_terminals
  ignore_errors: yes
  tags: hyprland

- name: Install terminal emulator packages (Debian/Ubuntu)
  ansible.builtin.apt:
    name: "{{ hyprland_terminals }}"
    state: present
  become: yes
  when: ansible_os_family == "Debian" and hyprland_install_terminals
  ignore_errors: yes
  tags: hyprland

- name: Create Hyprland config directory
  ansible.builtin.file:
    path: "{{ hyprland_config_dir }}"
    state: directory
    mode: '0755'
  tags: hyprland

- name: Create Hyprland wallpapers directory
  ansible.builtin.file:
    path: "{{ hyprland_config_dir }}/wallpapers"
    state: directory
    mode: '0755'
  tags: hyprland

- name: Create Waybar config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/waybar"
    state: directory
    mode: '0755'
  when: hyprland_install_status_bars
  tags: hyprland

- name: Create Mako config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/mako"
    state: directory
    mode: '0755'
  when: hyprland_install_notifications
  tags: hyprland

- name: Deploy Waybar configuration
  ansible.builtin.template:
    src: waybar_config.json.j2
    dest: "{{ ansible_env.HOME }}/.config/waybar/config"
    mode: '0644'
  when: hyprland_install_status_bars
  tags: hyprland

- name: Deploy Mako configuration
  ansible.builtin.template:
    src: mako_config.j2
    dest: "{{ ansible_env.HOME }}/.config/mako/config"
    mode: '0644'
  when: hyprland_install_notifications
  tags: hyprland

- name: Deploy Hyprpaper configuration
  ansible.builtin.template:
    src: hyprpaper_config.j2
    dest: "{{ hyprland_config_dir }}/hyprpaper.conf"
    mode: '0644'
  when: hyprland_install_core
  tags: hyprland

- name: Deploy Hypridle configuration
  ansible.builtin.template:
    src: hypridle_config.j2
    dest: "{{ hyprland_config_dir }}/hypridle.conf"
    mode: '0644'
  when: hyprland_install_core
  tags: hyprland

- name: Deploy Hyprlock configuration
  ansible.builtin.template:
    src: hyprlock_config.j2
    dest: "{{ hyprland_config_dir }}/hyprlock.conf"
    mode: '0644'
  when: hyprland_install_core
  tags: hyprland

- name: Enable user services for Hyprland utilities
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: yes
    scope: user
  loop:
    - mako
    - clipman
  ignore_errors: yes
  tags: hyprland