---
- name: Configure Dotfiles
  hosts: all
  gather_facts: true
  
  roles:
    - role: dotfiles
      tags: ['dotfiles']
    - role: shell
      tags: ['shell']
  
  post_tasks:
    - name: Verify dotfiles configuration
      ansible.builtin.debug:
        msg: "Dotfiles configured successfully"