---
- hosts: all
  connection: ssh
  gather_facts: true
  vars:
    dotfiles_repo_path: "{{ playbook_dir }}"
  tasks:
    - name: Find all dotfile directories
      ansible.builtin.find:
        paths: "{{ dotfiles_repo_path }}/config"
        file_type: directory
        depth: 1
      register: dotfile_dirs
    - name: Set config_dirs fact
      ansible.builtin.set_fact:
        config_dirs: "{{ dotfile_dirs.files | map(attribute='path') | map('basename') | list }}"
    - name: Create .config directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory

    - name: Check which tools are installed
      ansible.builtin.command: which {{ item }}
      register: tool_check
      failed_when: false
      changed_when: false
      loop:
        - zellij
        - helix
        - nvim
        - ghostty
        - starship
    - name: Create conditional config mapping
      ansible.builtin.set_fact:
        available_tools: "{{ tool_check.results | selectattr('rc', 'equalto', 0) | map(attribute='item') | list }}"

    - name: Symlink configs only for installed tools
      ansible.builtin.file:
        src: "{{ dotfiles_repo_path }}/config/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link
      loop: "{{ config_dirs | intersect(available_tools) }}"

    - name: Find shell dotfiles
      ansible.builtin.find:
        paths: "{{ dotfiles_repo_path }}/config/zsh"
        patterns: "*"
        file_type: file
      register: shell_files

    - name: Symlink shell files to home directory
      ansible.builtin.file:
        src: "{{ item.path }}"
        dest: "{{ ansible_env.HOME }}/.{{ item.path | basename }}"
        state: link
        force: yes
        follow: false
      loop: "{{ shell_files.files }}"

    - name: Symlink git config
      ansible.builtin.file:
        src: "{{ dotfiles_repo_path }}/dotfiles/git/gitconfig"
        dest: "{{ ansible_env.HOME }}/.gitconfig"
        state: link
        force: yes
        follow: false
