---
- name: Install GUI Applications
  hosts: all
  gather_facts: true
  environment:
    HOMEBREW_NO_AUTO_UPDATE: "1"
  
  pre_tasks:
    - name: Update package cache
      ansible.builtin.include_tasks: tasks/update_cache.yml
      tags: always
    
    - name: Check for display
      ansible.builtin.fail:
        msg: "No display detected - GUI applications require a display environment"
      when: 
        - ansible_env.DISPLAY is not defined
        - ansible_os_family != "Darwin"
  
  roles:
    - role: package_manager
      tags: ['package_manager']
    - role: gui
      tags: ['gui']
  
  post_tasks:
    - name: Verify GUI installation
      ansible.builtin.debug:
        msg: "GUI applications installed successfully"