[project]
name = "ansible-dotfiles"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = []

[dependency-groups]
dev = [
    "ansible-lint>=25.6.1",
    "molecule-plugins[podman]>=23.7.0",
    "molecule[podman]>=25.6.0",
    "yamllint>=1.37.1",
]
