---
- name: Configure machine with domain-based setup
  hosts: localhost
  gather_facts: yes
  vars:
    dotfiles_repo_path: "{{ playbook_dir }}/dotfiles"
  
  tasks:
    - name: Load domain tasks
      include_role:
        name: "{{ item }}"
      loop: "{{ domains }}"
      when: domains is defined
    
    - name: Setup dotfiles symlinks
      include_tasks: playbooks/dotfiles.yml
      when: domains is defined and 'base' in domains