---
# Main site playbook - orchestrates all configuration
- import_playbook: bootstrap.yml
  tags: ['bootstrap', 'all']

- import_playbook: base.yml
  tags: ['base']

- import_playbook: dev.yml
  tags: ['dev']

- import_playbook: gui.yml
  tags: ['gui']

- import_playbook: dotfiles.yml
  tags: ['dotfiles']

- import_playbook: maintenance.yml
  tags: ['maintenance']