---
- name: Configure machine with domain-based setup
  hosts: all
  gather_facts: yes
  vars:
    dotfiles_repo_path: "{{ playbook_dir }}"
    is_local_machine: "{{ inventory_hostname == 'localhost' or inventory_hostname == ansible_hostname }}"

  roles:
    - role: base
      when: domains is defined and 'base' in domains
      tags: base
    - role: development
      when: domains is defined and 'development' in domains
      tags: development
    - role: gui
      when: domains is defined and 'gui' in domains
      tags: gui

- import_playbook: playbooks/dotfiles.yml
  when: domains is defined and 'base' in domains

