version: '3'

tasks:
  install-deps:
    desc: Install Ansible Galaxy collections
    cmd: ansible-galaxy collection install -r requirements.yml

  macos:
    desc: Configure all macOS machines (hera, etc.)
    deps: [install-deps]
    cmd: ansible-playbook -i machines/macos.yml site.yml

  linux:
    desc: Configure all Linux machines (athena, etc.)
    deps: [install-deps]
    cmd: ansible-playbook -i machines/linux.yml site.yml

  base:
    desc: Install base domain only
    deps: [install-deps]
    vars:
      OS_FILE:
        sh: 'if [[ "$(uname -s)" == "Darwin" ]]; then echo "macos"; else echo "linux"; fi'
    cmd: ansible-playbook -i machines/{{.OS_FILE}}.yml site.yml --tags base

  development:
    desc: Install development domain only
    deps: [install-deps]
    vars:
      OS_FILE:
        sh: 'if [[ "$(uname -s)" == "Darwin" ]]; then echo "macos"; else echo "linux"; fi'
    cmd: ansible-playbook -i machines/{{.OS_FILE}}.yml site.yml --tags development

  gui:
    desc: Install GUI domain only
    deps: [install-deps]
    vars:
      OS_FILE:
        sh: 'if [[ "$(uname -s)" == "Darwin" ]]; then echo "macos"; else echo "linux"; fi'
    cmd: ansible-playbook -i machines/{{.OS_FILE}}.yml site.yml --tags gui

  dotfiles:
    desc: Setup dotfiles only (legacy)
    deps: [install-deps]
    vars:
      OS_FILE:
        sh: 'if [[ "$(uname -s)" == "Darwin" ]]; then echo "macos"; else echo "linux"; fi'
    cmd: ansible-playbook -i machines/{{.OS_FILE}}.yml playbooks/dotfiles.yml

  dotfiles-conditional:
    desc: Setup conditional dotfiles (only for installed tools)
    deps: [install-deps]
    vars:
      OS_FILE:
        sh: 'if [[ "$(uname -s)" == "Darwin" ]]; then echo "macos"; else echo "linux"; fi'
    cmd: ansible-playbook -i machines/{{.OS_FILE}}.yml dotfiles.yml

  check:
    desc: Validate Ansible syntax
    vars:
      OS_FILE:
        sh: 'if [[ "$(uname -s)" == "Darwin" ]]; then echo "macos"; else echo "linux"; fi'
    cmd: ansible-playbook --syntax-check -i machines/{{.OS_FILE}}.yml site.yml

  dry-run:
    desc: Preview changes without applying
    deps: [install-deps]
    vars:
      OS_FILE:
        sh: 'if [[ "$(uname -s)" == "Darwin" ]]; then echo "macos"; else echo "linux"; fi'
    cmd: ansible-playbook -i machines/{{.OS_FILE}}.yml site.yml --check --diff

  clean:
    desc: Clean broken symlinks in home directory (dotfiles only)
    cmd: find ~ -maxdepth 3 -name ".*" -type l ! -exec test -e {} \; -delete 2>/dev/null || true

