version: '3'

tasks:
  install-deps:
    desc: Install Ansible Galaxy collections
    cmd: ansible-galaxy collection install -r requirements.yml

  macos:
    desc: Configure macOS machine
    deps: [install-deps]
    cmd: ansible-playbook -i machines/macos.yml site.yml

  linux:
    desc: Configure Linux machine  
    deps: [install-deps]
    cmd: ansible-playbook -i machines/linux.yml site.yml

  base:
    desc: Install base domain only
    deps: [install-deps]
    cmd: ansible-playbook -i machines/{{OS}}.yml site.yml --tags base

  development:
    desc: Install development domain only
    deps: [install-deps]
    cmd: ansible-playbook -i machines/{{OS}}.yml site.yml --tags development

  gui:
    desc: Install GUI domain only
    deps: [install-deps]
    cmd: ansible-playbook -i machines/{{OS}}.yml site.yml --tags gui

  dotfiles:
    desc: Setup dotfiles only
    deps: [install-deps]
    cmd: ansible-playbook -i machines/{{OS}}.yml playbooks/dotfiles.yml

  check:
    desc: Validate Ansible syntax
    cmd: ansible-playbook --syntax-check -i machines/{{OS}}.yml site.yml

  dry-run:
    desc: Preview changes without applying
    deps: [install-deps]
    cmd: ansible-playbook -i machines/{{OS}}.yml site.yml --check --diff

  clean:
    desc: Clean broken symlinks
    cmd: find ~ -xtype l -delete

vars:
  OS: '{{.OS | default "linux"}}'