version: '3'

vars:
  INVENTORY: localhost

tasks:
  deps:
    desc: Install Ansible Galaxy collections
    cmd: ansible-galaxy collection install -r requirements.yml

  pkg:
    desc: Install specific domain
    deps: [deps]
    cmd: ansible-playbook -i inventory/{{.INVENTORY}}.yml site.yml --tags {{.CLI_ARGS}}

  all:
    desc: Install all domains (base, development, gui)
    deps: [deps]
    cmd: ansible-playbook -i inventory/{{.INVENTORY}}.yml site.yml
  dot:
    desc: Setup conditional dotfiles (only for installed tools)
    deps: [deps]
    cmd: ansible-playbook -i inventory/{{.INVENTORY}}.yml dotfiles.yml

  check:
    desc: Validate Ansible syntax
    cmd: ansible-playbook --syntax-check -i inventory/{{.INVENTORY}}.yml site.yml

  dry-run:
    desc: Preview changes without applying
    deps: [deps]
    cmd: ansible-playbook -i inventory/{{.INVENTORY}}.yml site.yml --check --diff

  clean:
    desc: Clean broken symlinks in home directory (dotfiles only)
    cmd: find ~ -maxdepth 3 -name ".*" -type l ! -exec test -e {} \; -delete 2>/dev/null || true

