---
- name: Create common directories
  ansible.builtin.file:
    path: "{{ directory }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ansible_env.HOME }}/.local/bin"
    - "{{ ansible_env.HOME }}/.config"
    - "{{ ansible_env.HOME }}/.cache"
  loop_control:
    loop_var: directory

- name: Install base CLI packages (macOS)
  community.general.homebrew:
    name: "{{ base_packages }}"
    state: present
  when: ansible_os_family == "Darwin"
- name: Install Starship
  ansible.builtin.shell: |
    curl -sS https://starship.rs/install.sh | sh -s -- --yes
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/starship"
- name: Install base CLI packages (Linux)
  ansible.builtin.dnf:
    name: "{{ base_packages | map('regex_replace', '^fd$', fd_package | default('fd')) | list }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

