---
# Main inventory file - organize machines by type and environment
all:
  children:
    # Machine types
    workstations:
      children:
        developers:
          hosts:
            hera:
              ansible_host: localhost
              ansible_connection: local
              machine_profile: developer
              os_type: darwin
        designers:
          hosts:
            # Add designer machines here
        servers:
          hosts:
            # Add server machines here
    
    # Environment groups
    local:
      children:
        workstations:
    
    homelab:
      hosts:
        athena:
          ansible_user: disco
          machine_profile: linux_workstation
          os_type: linux
    
    # OS-specific groups
    darwin:
      hosts:
        hera:
    
    linux:
      hosts:
        athena:
    
    # Role-specific groups
    development:
      children:
        developers:
    
    gui_machines:
      children:
        workstations:
    
    minimal:
      hosts:
        # Add minimal/headless machines here