all:
  hosts:
    athena:
      ansible_host: athena.local
      ansible_user: disco
      ansible_connection: ssh

      machine_type: linux
      domains: [base, development, gui]
      mise_languages:
        - name: go
          version: latest
        - name: python
          version: latest
        - name: zig
          version: "master"
