all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: auto_silent
      machine_type: "{{ 'macos' if ansible_os_family == 'Darwin' else 'linux' }}"
      domains: [base, development, gui]
      mise_languages:
        - name: go
          version: latest
        - name: python
          version: latest
        - name: zig
          version: 'master'
