---
- name: Clean package manager cache (macOS)
  ansible.builtin.shell: |
    brew cleanup --prune=all
  when: ansible_os_family == "Darwin"

- name: Clean package manager cache (Fedora/RedHat)
  ansible.builtin.dnf:
    autoremove: true
  become: true
  when: ansible_os_family == "RedHat"

- name: Clean Ansible cache
  ansible.builtin.shell: |
    rm -rf ~/.ansible/tmp/* 2>/dev/null || true