---
- name: Clean package manager cache (macOS)
  ansible.builtin.shell: |
    {{ homebrew_path | default('/opt/homebrew') }}/bin/brew cleanup --prune=all
    {{ homebrew_path | default('/opt/homebrew') }}/bin/brew autoremove
  when: ansible_os_family == "Darwin"
  environment:
    PATH: "{{ homebrew_path | default('/opt/homebrew') }}/bin:{{ ansible_env.PATH }}"

- name: Clean package manager cache (Fedora/RedHat)
  ansible.builtin.dnf:
    autoremove: true
  become: true
  when: ansible_os_family == "RedHat"

- name: Clean Ansible cache
  ansible.builtin.shell: |
    rm -rf ~/.ansible/tmp/* 2>/dev/null || true