---
- name: Check tool installation status
  ansible.builtin.shell: |
    tools=("git" "curl" "bat" "rg" "fzf" "nvim" "tmux" "go" "python3" "node" "podman")
    for tool in "${tools[@]}"; do
      if command -v "$tool" >/dev/null 2>&1; then
        echo "✅ $tool installed"
      else
        echo "❌ $tool not found"
      fi
    done
  register: tool_status
  changed_when: false
  tags: ['status']

- name: Display tool status
  ansible.builtin.debug:
    msg: "{{ tool_status.stdout_lines }}"
  tags: ['status']

- name: Show machine configuration
  ansible.builtin.debug:
    msg:
      - "Machine: {{ inventory_hostname }}"
      - "Profile: {{ machine_profile | default('default') }}"
      - "OS: {{ ansible_os_family }}"
      - "Architecture: {{ ansible_architecture }}"
      - "Container Runtime: {{ container_runtime }}"
  tags: ['status']