---
- name: Create .config directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config"
    state: directory
    mode: '0755'

- name: Create config subdirectories
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item.path | dirname }}"
    state: directory
    mode: '0755'
  loop: "{{ dotfiles }}"
  when:
    - item.path | dirname != '.'
    - item.path | dirname != '.config'

- name: Symlink dotfiles
  ansible.builtin.file:
    src: "{{ config_source_dir }}/{{ item.src }}"
    dest: "{{ ansible_env.HOME }}/{{ item.path }}"
    state: link
    force: true
  loop: "{{ dotfiles }}"


