---
- name: Install Go (macOS)
  community.general.homebrew:
    name: go
    state: present
  when: ansible_os_family == "Darwin"

- name: Install Go (Linux)
  ansible.builtin.dnf:
    name: golang
    state: present
  become: yes
  when: ansible_os_family == "RedHat"

- name: Create GOPATH directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/go"
    state: directory
    mode: '0755'

- name: Add Go to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.local/bin/environment"
    line: 'export PATH="$HOME/go/bin:$PATH"'
    create: yes