---
- name: Install Zig (macOS)
  community.general.homebrew:
    name: 
      - zig
      - zls
    state: present
  when: ansible_os_family == "Darwin"

- name: Install Zig (Linux)
  ansible.builtin.get_url:
    url: https://ziglang.org/download/0.12.0/zig-linux-x86_64-0.12.0.tar.xz
    dest: /tmp/zig.tar.xz
    mode: '0644'
  when: ansible_os_family == "RedHat"

- name: Extract Zig (Linux)
  ansible.builtin.unarchive:
    src: /tmp/zig.tar.xz
    dest: "{{ ansible_env.HOME }}/.local"
    remote_src: yes
    creates: "{{ ansible_env.HOME }}/.local/zig-linux-x86_64-0.12.0"
  when: ansible_os_family == "RedHat"

- name: Symlink Zig binary (Linux)
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/zig-linux-x86_64-0.12.0/zig"
    dest: "{{ ansible_env.HOME }}/.local/bin/zig"
    state: link
  when: ansible_os_family == "RedHat"

- name: Install ZLS (Linux)
  ansible.builtin.shell: |
    ZLS_VERSION=$(curl -s "https://api.github.com/repos/zigtools/zls/releases/latest" | grep -Po '"tag_name": "\K[^"]*')
    curl -Lo /tmp/zls.tar.xz "https://github.com/zigtools/zls/releases/latest/download/zls-x86_64-linux.tar.xz"
    tar xf /tmp/zls.tar.xz -C {{ ansible_env.HOME }}/.local/bin zls
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/zls"
  when: ansible_os_family == "RedHat"