---
- name: Check if display is available
  ansible.builtin.debug:
    msg: "Display available: {{ has_display }}"

- name: Install GUI packages (macOS)
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: present
  loop: "{{ gui_packages_combined }}"
  when: 
    - ansible_os_family == "Darwin"
    - has_display
    - gui_packages_combined is defined
    - gui_packages_combined | length > 0

- name: Install GUI packages (Linux)
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpak_apps }}"
  when: 
    - ansible_os_family != "Darwin"
    - has_display
    - flatpak_apps is defined

- name: Install macOS App Store applications
  community.general.mas:
    id: "{{ item.id }}"
    state: present
  loop: "{{ mas_apps }}"
  when: 
    - ansible_os_family == "Darwin"
    - has_display
    - mas_apps is defined
    - mas_apps | length > 0

- name: Configure desktop environment
  ansible.builtin.include_tasks: desktop.yml
  when: 
    - ansible_os_family != "Darwin"
    - has_display
    - window_manager is defined