# Starship configuration - Catppuccin Macchiato theme
# Minimal developer setup

"$schema" = 'https://starship.rs/config-schema.json'

# Minimal format - just essentials
format = """
$directory\
$git_branch\
$git_status\
$golang\
$python\
$cmd_duration\
$line_break\
$character\
"""

# Don't print a new line at the start
add_newline = false

# Use Catppuccin Macchiato color palette
palette = "catppuccin_macchiato"

# Prompt character
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

# Directory - show only last component
[directory]
truncation_length = 1
style = "bold blue"

# Git branch - minimal display
[git_branch]
symbol = "🌿 "
format = "on [$symbol$branch]($style) "
style = "bold mauve"

# Git status - concise indicators
[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold red"
staged = "+"
untracked = "?"
modified = "*"
renamed = "»"
deleted = "✘"
conflicted = "⚡"
ahead = "⇡${count}"
behind = "⇣${count}"

# Go - only in Go projects
[golang]
symbol = "🐹 "
format = "via [$symbol($version )]($style)"
style = "bold teal"
detect_extensions = ["go"]
detect_files = ["go.mod", "go.sum"]

# Python - UV-aware, only in Python projects
[python]
symbol = "🐍 "
format = 'via [$symbol$pyenv_prefix($version )(\($virtualenv\) )]($style)'
style = "bold yellow"
detect_extensions = ["py"]
detect_files = ["requirements.txt", "pyproject.toml", "Pipfile", "uv.lock"]

# Command duration - only for slow commands
[cmd_duration]
min_time = 1000
format = "took [$duration]($style) "
style = "yellow"

# Catppuccin Macchiato color palette
[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
