---
galaxy_info:
  author: disco
  description: Unified package management across platforms
  company: Personal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - package
    - homebrew
    - apt
    - dnf
    - system

dependencies: []

collections:
  - community.general
  - ansible.builtin