---
- name: Update system packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
  become: true

- name: Enable RPM Fusion repositories
  ansible.builtin.dnf:
    name:
      - "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ansible_distribution_major_version}}.noarch.rpm"
      - "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ansible_distribution_major_version}}.noarch.rpm"
    state: present
    disable_gpg_check: true
  become: true

- name: Enable COPR repositories
  community.general.copr:
    name: "{{ item }}"
    state: enabled
  loop: "{{ copr_repos }}"
  become: true

- name: Install DNF packages
  ansible.builtin.dnf:
    name: "{{ dnf_packages }}"
    state: present
  become: true

- name: Add Flathub repository
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.repo
  when: flatpak_packages | length > 0

- name: Install Flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  loop: "{{ flatpak_packages }}"
  when: flatpak_packages | length > 0

