# Helix Configuration
# Modern modal editor with built-in LSP support

# Theme
theme = "catppuccin_macchiato"

[editor]
# Basic editor settings
line-number = "relative"
mouse = true
scrolloff = 8
shell = ["zsh", "-c"]
text-width = 100
auto-completion = true
auto-format = true
auto-save = true
idle-timeout = 250
rulers = [80, 100]
gutters = ["diff", "diagnostics", "line-numbers", "spacer"]
true-color = true
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name", "file-modification-indicator"]
center = ["file-type"]
right = ["diagnostics", "selections", "position", "file-encoding"]
separator = "│"

[editor.lsp]
enable = true
display-messages = true
auto-signature-help = true
display-inlay-hints = true
display-signature-help-docs = true
snippets = true
goto-reference-include-declaration = true

[editor.search]
smart-case = true
wrap-around = true


[editor.indent-guides]
render = true
character = "╎"
skip-levels = 1

[editor.soft-wrap]
enable = true
max-wrap = 25
max-indent-retain = 0
wrap-indicator = "↪ "
wrap-at-text-width = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
follow-symlinks = true
deduplicate-links = true
parents = true
ignore = true
git-ignore = true
git-global = true
git-exclude = true
max-depth = 25

# Key bindings
[keys.normal]
# Leader key mappings (space)
[keys.normal.space]
f = { f = "file_picker", r = "file_picker_in_current_buffer_directory", g = "global_search" }
b = { b = "buffer_picker", n = "goto_next_buffer", p = "goto_previous_buffer" }
e = "toggle_comments"
s = "split_selection"
r = "rename_symbol"
a = "code_action"
d = "diagnostics_picker"
g = { g = "goto_line_start", e = "goto_line_end_newline" }
h = "jump_view_left"
j = "jump_view_down"
k = "jump_view_up"
l = "jump_view_right"
# Markdown specific bindings
m = { p = ":sh pandoc % -s --highlight-style=pygments -o /tmp/$(basename % .md).html && open /tmp/$(basename % .md).html", g = ":sh gh markdown-preview %", f = ":set-option soft-wrap.enable true" }

# Window management
[keys.normal.C-w]
h = "jump_view_left"
j = "jump_view_down"
k = "jump_view_up"
l = "jump_view_right"
s = "hsplit"
v = "vsplit"
q = "wclose"
o = "wonly"

# Insert mode mappings
[keys.insert]
"C-c" = "normal_mode"
"C-w" = "delete_word_backward"
"C-u" = "kill_to_line_start"
"C-k" = "kill_to_line_end"
"C-j" = "completion"
"C-space" = "completion"
# Markdown link insertion
#"A-l" = "insert_char('[[')"

# Select mode mappings
[keys.select]
"C-c" = "normal_mode"
"y" = ["yank", "normal_mode"]
"d" = ["delete_selection", "normal_mode"]
"c" = ["change_selection"]

# Markdown-specific settings
#[editor.file-types]
#[editor.file-types.markdown]
#soft-wrap = { enable = true, wrap-at-text-width = true }
#text-width = 80
#completion-timeout = 250
