---
driver:
  name: podman
platforms:
  - name: fedora-dev
    image: fedora:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
    tmpfs:
      - /run
      - /tmp
    groups:
      - linux
      - development
provisioner:
  name: ansible
  inventory:
    host_vars:
      fedora-dev:
        ansible_user: root
        machine_profile: linux_workstation
        os_type: linux
    group_vars:
      development:
        enable_development_tools: true
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
dependency:
  name: galaxy
  options:
    requirements-file: ../../requirements.yml
