---
galaxy_info:
  author: disco
  description: Development tools and environment
  company: Personal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - development
    - programming
    - tools

dependencies:
  - role: package_manager
  - role: base

collections:
  - community.general
  - ansible.builtin