---
- name: Create base directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ base_directories }}"

- name: Install base packages
  ansible.builtin.include_role:
    name: package_manager
  vars:
    packages_to_install: "{{ base_packages_combined }}"
    cask_packages_to_install: "{{ macos_applications | default([]) }}"

- name: Add local bin to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: true
  when: ansible_os_family != "Darwin"

- name: Set up shell environment
  ansible.builtin.template:
    src: environment.j2
    dest: "{{ ansible_env.HOME }}/.environment"
    mode: '0644'
  when: create_environment_file | default(true)