---
- name: Create base directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ base_directories }}"

# Note: Base packages are now installed by package_manager role to avoid duplicates

- name: Add local bin to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: true
  when: ansible_os_family != "Darwin"

- name: Set up shell environment
  ansible.builtin.template:
    src: environment.j2
    dest: "{{ ansible_env.HOME }}/.environment"
    mode: '0644'
  when: create_environment_file | default(true)