---
galaxy_info:
  author: disco
  description: Base system packages and configuration
  company: Personal
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: MacOSX
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - base
    - system
    - packages

dependencies:
  - role: package_manager

collections:
  - community.general
  - ansible.builtin