---
- name: Install Go (macOS)
  community.general.homebrew:
    name: go
    state: present
  when: ansible_os_family == "Darwin"

- name: Install Go (Linux)
  ansible.builtin.package:
    name: golang-go
    state: present
  become: true
  when: ansible_os_family != "Darwin"

- name: Set up Go environment
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zprofile"
    line: "{{ item.line }}"
    regexp: "{{ item.regexp }}"
    create: true
  loop:
    - { line: 'export GOPATH="$HOME/go"', regexp: '^export GOPATH=' }
    - { line: 'export PATH="$GOPATH/bin:$PATH"', regexp: '^export PATH=.*GOPATH.*' }

- name: Check if Go tools are installed
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/go/bin/{{ item | basename }}"
  loop:
    - gopls
    - golangci-lint
  register: go_tools_check

- name: Install common Go tools
  ansible.builtin.shell: |
    go install {{ item.item }}
  loop:
    - { item: "golang.org/x/tools/gopls@latest", basename: "gopls" }
    - { item: "github.com/golangci/golangci-lint/cmd/golangci-lint@latest", basename: "golangci-lint" }
  environment:
    GOPATH: "{{ ansible_env.HOME }}/go"
    PATH: "{{ ansible_env.HOME }}/go/bin:{{ ansible_env.PATH }}"
  when: not (go_tools_check.results | selectattr('item', 'equalto', item.basename) | first).stat.exists