---
- name: Create development directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop: "{{ dev_directories }}"

- name: Install development packages
  ansible.builtin.include_role:
    name: package_manager
  vars:
    packages_to_install: "{{ dev_packages_combined }}"

- name: Set up Go environment
  ansible.builtin.include_tasks: go.yml
  when: language_setup.go.enabled

- name: Set up Python environment
  ansible.builtin.include_tasks: python.yml
  when: language_setup.python.enabled

- name: Set up Node.js environment
  ansible.builtin.include_tasks: node.yml
  when: language_setup.node.enabled

- name: Set up Rust environment
  ansible.builtin.include_tasks: rust.yml
  when: language_setup.rust.enabled

- name: Setup container runtime (Linux)
  ansible.builtin.include_tasks: container.yml
  when: ansible_os_family != "Darwin"

- name: Configure Git
  community.general.git_config:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    scope: global
  loop:
    - { name: "init.defaultBranch", value: "main" }
    - { name: "pull.rebase", value: "true" }
    - { name: "fetch.prune", value: "true" }

- name: Configure development shell
  ansible.builtin.template:
    src: dev_aliases.j2
    dest: "{{ ansible_env.HOME }}/.dev_aliases"
    mode: '0644'