---
- hosts: localhost
  connection: local
  gather_facts: true
  vars:
    # Dynamically discover all directories in config/ to symlink to ~/.config/
    dotfiles_repo_path: "{{ playbook_dir | dirname }}"
    
    # Special files that need individual handling
    special_files:
      # .zprofile goes to HOME directory
      ".zprofile": "{{ ansible_env.HOME }}/.zprofile"
      # .zshenv goes to HOME directory to set ZDOTDIR
      ".zshenv": "{{ ansible_env.HOME }}/.zshenv"
      # zshrc goes to ZDOTDIR as .zshrc
      "zsh/zshrc": "{{ ansible_env.HOME }}/.config/zsh/.zshrc"
      # catppuccin theme goes to zellij themes directory
      "catppuccin-macchiato.kdl": "{{ ansible_env.HOME }}/.config/zellij/themes/catppuccin-macchiato.kdl"

  tasks:
    - name: Discover config directories
      ansible.builtin.find:
        paths: "{{ dotfiles_repo_path }}/config"
        file_type: directory
        depth: 1
      register: config_directories

    - name: Set config_dirs fact
      ansible.builtin.set_fact:
        config_dirs: "{{ config_directories.files | map(attribute='path') | map('basename') | list | difference(['zsh']) }}"

    - name: Ensure ~/.config directory exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config"
        state: directory
        mode: '0755'

    - name: Create zellij themes directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/zellij/themes"
        state: directory
        mode: '0755'

    - name: Create zsh config directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/zsh"
        state: directory
        mode: '0755'

    - name: Remove existing config directory symlinks to avoid conflicts
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: absent
      loop: "{{ config_dirs }}"

    - name: Create symlinks for all config directories
      ansible.builtin.file:
        src: "{{ dotfiles_repo_path }}/config/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.config/{{ item }}"
        state: link
        force: yes
        follow: false
      loop: "{{ config_dirs }}"

    - name: Remove existing special file symlinks to avoid conflicts
      ansible.builtin.file:
        path: "{{ item.value }}"
        state: absent
      loop: "{{ special_files | dict2items }}"

    - name: Create symlinks for special files
      ansible.builtin.file:
        src: "{{ dotfiles_repo_path }}/config/{{ item.key }}"
        dest: "{{ item.value }}"
        state: link
        force: yes
        follow: false
      loop: "{{ special_files | dict2items }}"