---
# Variables for Linux machines
os_family: Linux

# Linux-specific packages - consolidated from all sources
linux_packages_combined: >
  {{
    (base_packages | default([])) +
    (workstation_packages | default([])) +
    (development_tools | default([])) +
    (container_tools | default([])) +
    (['gcc', 'gcc-c++', 'make', 'pkgconf', 'fd-find', 'openssl-devel', 'readline-devel', 'zlib-devel', 'ncurses-devel', 'libffi-devel', 'gdbm-devel', 'libyaml-devel', 'sqlite-devel'])
  }}

# Package manager specifics
redhat_packages:
  - gcc
  - gcc-c++
  - make
  - pkgconf

# Flatpak applications for Linux GUI (only for package_manager role)
flatpak_applications: []

# System services
system_services:
  - name: podman
    state: started
    enabled: true

# Desktop environment packages
desktop_packages:
  - hyprland
  - waybar
  - mako
  - wofi
  - grim
  - slurp
  - wl-clipboard
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk
  - hyprlock
  - hypridle
  - hyprpaper
  - polkit-gnome
  - pipewire
  - pipewire-pulseaudio
  - brightnessctl
  - playerctl
  - foot
  - pavucontrol