---
# Variables for all workstation machines
machine_type: workstation

# Workstation-specific packages
workstation_packages:
  - jq
  - bat
  - ripgrep
  - fzf
  - fd

# GUI applications for workstations
gui_applications:
  Darwin:
    - firefox
    - discord
    - obsidian
    - ghostty
    - raycast
    - goland
    - pycharm
    - zed
  Linux:
    - org.mozilla.firefox
    - com.visualstudio.code
    - com.discordapp.Discord
    - com.slack.Slack
    - md.obsidian.Obsidian
    - com.jetbrains.GoLand
    - com.jetbrains.PyCharm-Community

# Development tools for workstations
development_tools:
  - neovim
  - tmux
  - git
  - gh
  - direnv

# Shell configuration
shell_config:
  default_shell: zsh
  install_oh_my_zsh: true
